# Generated by Django 6.0.4 on 2026-07-01 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa04', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missão',
            options={'verbose_name': 'Missão', 'verbose_name_plural': 'Missões'},
        ),
    ]
