# Generated by Django 6.0.4 on 2026-07-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('imagem', models.ImageField(upload_to='imgs/')),
                ('data_publicacao', models.DateField()),
            ],
        ),
    ]
